"""Change mesa_numero to mesas for multi-table reservations

Revision ID: 2aa28a48c126
Revises: 2b1554101018
Create Date: 2026-02-06 20:23:54.497841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa28a48c126'
down_revision = '2b1554101018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mesas', sa.String(length=50), nullable=False))
        batch_op.drop_column('mesa_numero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mesa_numero', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('mesas')

    # ### end Alembic commands ###
